### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by roryphair** [roryphair/Disagree#3]
I believe I have all the rest of my mvps done, so I am requesting a review of those.

**Comment by kkossally** [comment]
- All functionality in your MVP list works well and your styling is good. Honestly, excellent work!

- [ ] center the '+' in the create server button

- [ ] style your message time stamps like the original (including day break borders)

- [ ] in the add server dialog, hovering over the two options changes their position

- [ ] in the same place as above, use a softer border shadow that is on all sides of the button

- [ ] style the relevant parts of your create server and create channel dialogs more faithfully

- [ ] when hovering over server icons, transition to a squarish shape rather than changing the border color (I think you had it that way earlier in the project)

## Styling to make your clone feel more like Discord

- [ ] Discord seems to prefer a lowercase, slightly smaller, sans-serif font for most text

- [ ] match the widths of the different sections more precisely

- [ ] consider adding friends as a bonus MVP
